location = /cd/deploy {
  limit_req zone=auth burst=2;

  client_max_body_size 2k;
  proxy_pass http://web_listener_backend/;
  include /etc/nginx/sites-available/proxy-common.inc;
  proxy_set_header Connection "";
  proxy_request_buffering on;
  proxy_buffering on;
  proxy_send_timeout 10s;
  proxy_read_timeout 30s;
}
