server {
	server_name ((SITE)).((DOMAIN));
	listen 8443 ssl;
	listen [::]:8443 ssl;
	http2 on;
	include /etc/nginx/sites-available/shared-ssl.inc;

	if ($block) { # set in badagents.conf
		return 444;
	}

	access_log off;
	error_log /var/log/nginx/error.log error;

	merge_slashes off;

	location / {
		limit_req zone=background burst=5000;

		client_max_body_size 128k;
		client_body_timeout 20s;
		proxy_pass http://web_listener_backend/((SITE))/;
		include /etc/nginx/sites-available/proxy-common.inc;
		proxy_set_header Connection "";
		proxy_request_buffering on;
		proxy_buffering on;
		proxy_send_timeout 10s;
		proxy_read_timeout 10s;
	}
}
