# since our swap is zram, we can have a high swappiness
# (but this has not been specifically tuned, and can probably be set higher)
vm.swappiness = 60 # default=60
vm.watermark_boost_factor = 0 # default=15000; do not attempt to defragment high / low-use parts of pageblocks
vm.watermark_scale_factor = 150 # default=10; swap once <1.5% memory remains
vm.page-cluster = 0 # default=3
