map $uri $asset_cache_control {
	~.*\.[0-9]+\.[^.]+$ "immutable, public, max-age=31536000, stale-while-revalidate=31536000, stale-if-error=31536000"; # versioned
	default "public, max-age=2592000, stale-while-revalidate=31536000, stale-if-error=31536000";
}
