location /assets/ {
	alias /var/www/assets/content/;
	add_header Cache-Control $asset_cache_control;
	add_header Cross-Origin-Embedder-Policy "require-corp";
	add_header Cross-Origin-Opener-Policy "same-origin";
	add_header Cross-Origin-Resource-Policy "same-origin";
	add_header Access-Control-Allow-Origin $allow_origin;
	add_header Vary Origin always;
	add_header Referrer-Policy "no-referrer" always;
	add_header X-Content-Type-Options "nosniff" always;
	add_header X-Clacks-Overhead "GNU Terry Pratchett" always;
}

location /schema/ {
	alias /var/www/assets/schema/;
	add_header Cache-Control "immutable, public, max-age=31536000, stale-while-revalidate=31536000, stale-if-error=31536000";
	add_header Cross-Origin-Embedder-Policy "require-corp";
	add_header Cross-Origin-Opener-Policy "same-origin";
	add_header Cross-Origin-Resource-Policy "same-origin";
	add_header Referrer-Policy "no-referrer" always;
	add_header X-Content-Type-Options "nosniff" always;
	add_header X-Clacks-Overhead "GNU Terry Pratchett" always;
}
