#!/bin/sh
set -ex

BASEDIR="$(dirname "$0")";
. "$BASEDIR/../common/utils.sh";
SERVICE_PORTS="4080 4081";

# Disable existing update mechanism (if present) to avoid conflicting actions

sudo systemctl disable --now refacto-updater.timer || true;

# Check / preserve secrets

if ! [ -f "$BASEDIR/../env/refacto.env" ]; then
  if ! [ -f /var/www/refacto/secrets.env ]; then
    set +x;
    echo "Must populate env/refacto.env" >&2;
    exit 1;
  fi;
  # Preserve existing secrets if re-installing without new secrets
  sudo cp /var/www/refacto/secrets.env "$BASEDIR/../env/refacto.env";
fi;
sudo chmod 0400 "$BASEDIR/../env/refacto.env";

# Is this the first install / a fresh install

LOAD_BACKUP=false;
if ! [ -f /etc/nginx/sites-available/refacto ]; then
  sudo rm -r /var/www/refacto || true;
  LOAD_BACKUP=true;

  # Shutdown existing services if found

  for PORT in $SERVICE_PORTS; do
    sudo systemctl stop "refacto$PORT.service" || true;
  done;
fi;

# Make users

if ! id -u refacto-updater >/dev/null 2>&1; then
  sudo useradd --create-home --user-group refacto-updater;
fi;
if ! id -u refacto-runner >/dev/null 2>&1; then
  sudo useradd --system --user-group refacto-runner;
fi;

# Load dependencies

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
  nodejs \
  mongodb-org-server \
  mongodb-database-tools \
  mongodb-mongosh \
  jq \
  build-essential;

# disable telemetry when using mongosh tool
mongosh --nodb --eval 'disableTelemetry()';

# set max connections (use mongosh --eval 'db.serverStatus().connections' to see current state)
if ! grep 'maxIncomingConnections' < /etc/mongod.conf > /dev/null; then
  sudo sed -i -e 's/^net\:/net\:\n  maxIncomingConnections: 1000/' /etc/mongod.conf;
fi;

# could configure transparent huge pages here for a performance boost:
# https://www.mongodb.com/docs/manual/administration/tcmalloc-performance/#enable-transparent-hugepages--thp-

# remove deprecated feature to reduce attack surface
if ! grep 'javascriptEnabled' < /etc/mongod.conf > /dev/null; then
  printf '\nsecurity:\n  javascriptEnabled: false\n' | \
    sudo tee -a /etc/mongod.conf > /dev/null;
fi;

sudo systemctl enable --now mongod;

# Install boilerplate

sudo mkdir -p /var/www/refacto/update;
sudo chown -R refacto-updater:refacto-updater /var/www/refacto/update;

sudo mv "$BASEDIR/../env/refacto.env" /var/www/refacto/secrets.env;
sudo chown root:refacto-runner /var/www/refacto/secrets.env;
sudo chmod 0400 /var/www/refacto/secrets.env;

sudo cp "$BASEDIR/update.sh" /var/www/refacto/update.sh;
sudo chown root:refacto-updater /var/www/refacto/update.sh;
sudo chmod 0544 /var/www/refacto/update.sh;

sudo mkdir -p /var/log/refacto;
sudo chown -R refacto-runner:adm /var/log/refacto;
sudo chmod 0750 /var/log/refacto;

# Update to first version

sudo /var/www/refacto/update.sh --force --nostart;

# Import data

if [ "$LOAD_BACKUP" = "true" ]; then
  if [ -z "$REFACTO_DATA_FILE" ]; then
    set +x;
    echo;
    echo;
    echo "Enter filename to import refacto data from, or leave blank for no import:";
    echo "(this should be a .tar.gz file generated by the ./backup.sh script)";
    read REFACTO_DATA_FILE;
    set -x;
  fi;
  if [ -n "$REFACTO_DATA_FILE" ] && [ "$REFACTO_DATA_FILE" != "none" ]; then
    "$BASEDIR/restore.sh" "$REFACTO_DATA_FILE";
  fi;
fi;

# Configure mongo user-based access

if ! grep 'authorization: enabled' < /etc/mongod.conf > /dev/null; then
  # generated passwords are local to this deployment - they do not need to be copied to new instances, as the users will be created fresh
  ADMIN_PASSWORD="$(openssl rand -base64 30 | tr '/+' '_-')";
  ADMIN_PASSWORD_FILE="$BASEDIR/../env/mongo-admin-password";
  sudo touch "$ADMIN_PASSWORD_FILE";
  sudo chmod 0600 "$ADMIN_PASSWORD_FILE";
  echo "$ADMIN_PASSWORD" | sudo tee "$ADMIN_PASSWORD_FILE" > /dev/null;
  printf "%s\n" "$ADMIN_PASSWORD" | mongosh admin \
    --eval 'db.createUser({user:"admin",pwd:passwordPrompt(),roles:["root"],mechanisms:["SCRAM-SHA-256"]})';

  BACKUP_PASSWORD="$(openssl rand -base64 30 | tr '/+' '_-')";
  BACKUP_PASSWORD_FILE="$BASEDIR/../env/mongo-backup-password";
  sudo touch "$BACKUP_PASSWORD_FILE";
  sudo chmod 0600 "$BACKUP_PASSWORD_FILE";
  echo "$BACKUP_PASSWORD" | sudo tee "$BACKUP_PASSWORD_FILE" > /dev/null;
  printf "%s\n" "$ADMIN_PASSWORD" "$BACKUP_PASSWORD" | mongosh admin \
    --eval 'db.auth("admin",passwordPrompt())' \
    --eval 'db.createUser({user:"backup",pwd:passwordPrompt(),roles:["backup"],mechanisms:["SCRAM-SHA-256"]})';

  REFACTO_PASSWORD="$(openssl rand -base64 30 | tr '/+' '_-')";
  printf "%s\n" "$ADMIN_PASSWORD" "$REFACTO_PASSWORD" | mongosh admin \
    --eval 'db.auth("admin",passwordPrompt())' \
    --eval 'use refacto' \
    --eval 'db.createUser({user:"refacto",pwd:passwordPrompt(),roles:[{"db":"refacto","role":"readWrite"},{"db":"refacto","role":"dbAdmin"}],mechanisms:["SCRAM-SHA-256"]})';

  sudo sed -i -e 's/^security\:/security\:\n  authorization: enabled/' /etc/mongod.conf;

  sudo systemctl restart mongod;
  sudo sed -i -E 's/^DB_URL=mongodb:\/\/(.*@)?localhost:/DB_URL=mongodb:\/\/refacto:'"$REFACTO_PASSWORD"'@localhost:/' /var/www/refacto/secrets.env;
fi;

# Create and start services

for PORT in $SERVICE_PORTS; do
  NAME="refacto$PORT.service";
  LOGFILE="/var/log/refacto/refacto-$PORT.log"
  sudo touch -a "$LOGFILE";
  sudo chmod 0640 "$LOGFILE";
  sudo chown refacto-runner:adm "$LOGFILE";
  sed -e "s/((PORT))/$PORT/g" -e "s~((LOGFILE))~$LOGFILE~g" "$BASEDIR/refacto.service" | \
    sudo tee "/lib/systemd/system/$NAME" > /dev/null;
  sudo chmod 0644 "/lib/systemd/system/$NAME";
  sudo systemctl enable "$NAME";
  sudo systemctl restart "$NAME";
done;

# Configure auto-update

sudo cp "$BASEDIR/refacto-updater.service" "$BASEDIR/refacto-updater.timer" /lib/systemd/system/;
sudo chmod 0644 /lib/systemd/system/refacto-updater.service /lib/systemd/system/refacto-updater.timer;
sudo systemctl enable refacto-updater.timer; # no --now (do not start updater while we are still installing)

# Configure rotation of logs

install_config "$BASEDIR/logrotate/refacto" /etc/logrotate.d || true;

sudo cp "$BASEDIR/clean-mongo-log.sh" /var/www/refacto/clean-mongo-log.sh;
sudo chmod 0755 /var/www/refacto/clean-mongo-log.sh;
sudo cp "$BASEDIR/clean-mongo-log.service" "$BASEDIR/clean-mongo-log.timer" /lib/systemd/system/;
sudo chmod 0644 /lib/systemd/system/clean-mongo-log.service /lib/systemd/system/clean-mongo-log.timer;
sudo systemctl enable --now clean-mongo-log.timer;

# Add NGINX config

sed "s/((DOMAIN))/$DOMAIN/g" "$BASEDIR/site.conf" | \
  sudo tee /etc/nginx/sites-available/refacto > /dev/null;

sudo ln -s /etc/nginx/sites-available/refacto /etc/nginx/sites-ready/refacto;
