set -ex

BASEDIR="$(dirname "$0")";
SERVICE_PORTS="4080 4081";

if [[ ! -f "$BASEDIR/../env/refacto.env" ]]; then
  set +x;
  echo "Must populate env/refacto.env" >&2;
  exit 1;
fi;

# Make Users

sudo useradd --create-home --user-group --password '' refacto-updater || true;
sudo useradd --system --user-group --password '' refacto-runner || true;

# Load dependencies

sudo apt-get install -y nodejs mongodb jq;

# Install boilerplate

sudo rm -r /var/www/refacto || true;
sudo mkdir -p /var/www/refacto/logs;
sudo mv "$BASEDIR/../env/refacto.env" /var/www/refacto/secrets.env;
sudo cp "$BASEDIR/runner.sh" /var/www/refacto/runner.sh;
sudo cp "$BASEDIR/update.sh" /var/www/refacto/update.sh;

sudo chown root:refacto-runner /var/www/refacto/secrets.env /var/www/refacto/update.sh;
sudo chown refacto-updater:refacto-updater /var/www/refacto/current;
sudo chown -R refacto-runner:refacto-runner /var/www/refacto/logs;
sudo chown refacto-runner:refacto-runner /var/www/refacto/runner.sh;
sudo chmod 0400 /var/www/refacto/secrets.env;
sudo chmod 0544 /var/www/refacto/runner.sh /var/www/refacto/update.sh;

# Create new services

for PORT in $SERVICE_PORTS; do
  NAME="refacto$PORT.service";
  sed "s/((PORT))/$PORT/g" "$BASEDIR/refacto.svc" | \
    sudo tee "/lib/systemd/system/$NAME" > /dev/null;
  sudo chmod 0644 "/lib/systemd/system/$NAME";
  sudo systemctl enable "$NAME";
done;

# Update to first version

"$BASEDIR/update.sh" --force --nostart;

# Add NGINX config

sed "s/((DOMAIN))/$DOMAIN/g" "$BASEDIR/site.conf" | \
  sudo tee /etc/nginx/sites-available/refacto > /dev/null;

# Import data

set +x;
echo;
echo;
echo "Enter filename to import refacto data from, or leave blank for no import:";
echo "(this should be a .tar.gz file generated by the ./backup.sh script)";
read DATA_FILE;
set -x;
if [[ -n "$DATA_FILE" ]]; then
  "$BASEDIR/restore.sh" "$DATA_FILE";
fi;

# Start new services

for PORT in $SERVICE_PORTS; do
  sudo systemctl start "refacto$PORT.service";
done;

# Configure auto-update

sudo cp "$BASEDIR/refacto-pull" /etc/cron.daily/refacto-pull;
sudo chmod 0755 /etc/cron.daily/refacto-pull;
