location /retro/ {
	keepalive_timeout 0s;
	access_log off;
	expires max;
	return 301 https://retro.((DOMAIN))$request_uri;
}

location /retros/ {
	keepalive_timeout 0s;
	access_log off;
	expires max;
	return 301 https://retro.((DOMAIN))$request_uri;
}
